config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "restaurants", to: "restaurants#index"
  get "restaurants/new", to: "restaurants#new"
  post "restaurants", to: "restaurants#create"
  get "restaurants/:id", to: "restaurants#show", as: :restaurant

  get "/restaurants/:restaurant_id/reviews/new", to: "reviews#new", as: :restaurant_new_reviews
  post "/restaurants/:restaurant_id/reviews", to: "reviews#create", as: :restaurant_reviews
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :phone_number, presence: true

  CATEGORIES = %w[chinese italian japanese french belgian]
  validates :category, presence: true, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, presence:true,
  numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end
  def new
  @restaurant = Restaurant.new
  end

  def show
  @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container mt-4">
  <h1 class="mb-4">My restaurants</h1>

  <ul class="list-group mb-4">
    <% @restaurants.each do |restaurant| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <%= link_to restaurant.name, restaurant_path(restaurant), class: "text-decoration-none fw-semibold" %>
        <span class="text-muted small">
            <i class="bi bi-chevron-right"></i>
        </span>
      </li>
    <% end %>
  </ul>

  <%=link_to "Add a new restaurant", restaurants_new_path, class: "btn btn-primary"%>
</div>

app/views/restaurants/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6">

      <h1 class="mb-4">Add New Restaurant</h1>
      <%= simple_form_for(@restaurant) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :address %>
        <%= f.text_field :address %>
        <%= f.label :phone_number %>
        <%= f.number_field :phone_number %>
        <%= f.input :category,
                    collection: Restaurant::CATEGORIES,
                    prompt: "Select a category" %>
        <%= f.button :submit, "Create Restaurant", class: "btn btn-primary" %>
      <% end %>
      <br>
      <%= link_to "Back to list", restaurants_path, class: "btn btn-primary" %>

    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container mt-4">
  <div class="card mb-4 shadow-sm">
    <div class="card-body">

      <h1 class="card-title"><%= @restaurant.name %></h1>

      <i class="bi bi-geo-alt"></i>
      <p class="mb-1 text-muted">
        <%= @restaurant.address %>
      </p>

      <p class="mb-3 text-muted">
        <i class="bi bi-telephone"></i>
        <%= @restaurant.phone_number %>
      </p>

      <div class="d-flex gap-2">
        <%= link_to "Back to list", restaurants_path, class: "btn btn-primary" %>
        <%= link_to "Add a review", restaurant_new_reviews_path(@restaurant), class: "btn btn-primary mt-2 mb-2" %>
      </div>
    </div>
  </div>

  <div class="card shadow-sm">
    <div class="card-body">

      <h2 class="card-title mb-3">Reviews</h2>
      <ul class="list-group list-group-flush">
        <% @restaurant.reviews.each do |review| %>
          <li><%= review.content %></li>
        <% end %>
      </ul>

    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>
<br>
<%= link_to "Back to restaurant page", restaurant_path(@restaurant), class: "btn btn-primary" %>